// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUaN_bf7E9uWUS1Uo70d6U44S1ShetHzk',
    appId: '1:271773865581:web:9d0b9c173bb15ab186d164',
    messagingSenderId: '271773865581',
    projectId: 'practice-writing-app-c6bd8',
    authDomain: 'practice-writing-app-c6bd8.firebaseapp.com',
    storageBucket: 'practice-writing-app-c6bd8.firebasestorage.app',
    measurementId: 'G-YB2RKLXGZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-b71LGHvloxjUAg8kj-cV45G8itqaAN4',
    appId: '1:271773865581:android:df72f1526c57e48386d164',
    messagingSenderId: '271773865581',
    projectId: 'practice-writing-app-c6bd8',
    storageBucket: 'practice-writing-app-c6bd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChrYI-mhDauZQvjV3E6T06nSWj9E5EwV8',
    appId: '1:271773865581:ios:7fd72ebcff54ec5d86d164',
    messagingSenderId: '271773865581',
    projectId: 'practice-writing-app-c6bd8',
    storageBucket: 'practice-writing-app-c6bd8.firebasestorage.app',
    iosBundleId: 'com.example.writingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChrYI-mhDauZQvjV3E6T06nSWj9E5EwV8',
    appId: '1:271773865581:ios:7fd72ebcff54ec5d86d164',
    messagingSenderId: '271773865581',
    projectId: 'practice-writing-app-c6bd8',
    storageBucket: 'practice-writing-app-c6bd8.firebasestorage.app',
    iosBundleId: 'com.example.writingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUaN_bf7E9uWUS1Uo70d6U44S1ShetHzk',
    appId: '1:271773865581:web:5e3a739519a1ed5b86d164',
    messagingSenderId: '271773865581',
    projectId: 'practice-writing-app-c6bd8',
    authDomain: 'practice-writing-app-c6bd8.firebaseapp.com',
    storageBucket: 'practice-writing-app-c6bd8.firebasestorage.app',
    measurementId: 'G-4Y9GCC7VV3',
  );
}
