name: writing_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.2
  firebase_core: ^3.10.0 # Use for initializing Firebase
  firebase_auth: ^5.4.0 # Use for authentication with Firebase
  firebase_auth_web: ^5.13.6 # Firebase Authentication support for the web
  cloud_firestore: ^5.6.1 # Use for Firestore database
  firebase_storage: ^12.4.0 # Use for Firebase Storage
  google_sign_in: ^6.3.0
  confetti: ^0.7.0 # ใช้เวอร์ชันล่าสุด (อัปเดตเวอร์ชันจาก pub.dev ได้)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/evaluate_icon.png
    - assets/practice_icon.png
    - assets/Writing_1.png
    - assets/google_logo.png
    - assets/Thai/
    - assets/congrats.gif
    - assets/English/

  # To add assets to your application, uncomment and add paths here.
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Add custom fonts, uncomment and add your fonts here.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
# To initialize Firebase in the app, add this line in your main.dart (not in pubspec.yaml):
# await Firebase.initializeApp();
